# Production values for Time Wizard.

minReplicaCount: 3
maxReplicaCount: 5

cpuPercent: 75

image:
  repository: gcr.io/aurum-services/1x1
  tag: docker-config

resources:
  requests:
    cpu: 150m
    memory: 400Mi
  limits:
    cpu: 250m
    memory: 800Mi