apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: n1-highmem-4
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: {{ .Chart.Name }}
              containerPort: 5000
              protocol: TCP
          env:
            - name: API_PORT
              value: "3333"
          envFrom:
            - secretRef:
                name: 1x1-api-url
            - secretRef:
                name: 1x1-google-client-id
            - secretRef:
                name: 1x1-mongo-url
          resources:
            requests:
              cpu: 150m
              memory: 400Mi
            limits:
              cpu: 250m
              memory: 800Mi
