apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: feedback-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - feedback.aurum.com.br
    secretName: feedback-tls
  rules:
  - host: feedback.aurum.com.br
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80